#!/bin/bash
set -e
jlpm

# initially list installed extensions to determine if there are any surprises
jupyter labextension list

# install the labextension
jlpm pack
jupyter labextension install --no-build jlab-enhanced-launcher-*.tgz
jupyter labextension disable @jupyterlab/launcher-extension

# verify the list of extensions
jupyter labextension list

jupyter lab build --dev-build=False --minimize=True --debug

# verify the list of extensions one last time
jupyter labextension list
